import logic.main as scraping

LINE_NOTIFY_TOKEN = "53Ud7C6VSkTk2nbI3ooxQI02r2CvOzdmzl1Utjh85RK"
SEARCH_URL = "https://jp.mercari.com/search?keyword=チョロQアドバンス&status=on_sale"
LOOP_LIMIT = 10
PRICE_UPPER_LIMIT = 1101
PRICE_LOWER_LIMIT = 299
TIME_SLEEP = 3600
OVERLAP_LIMIT = 10

scraping.main(LINE_NOTIFY_TOKEN, SEARCH_URL, LOOP_LIMIT, PRICE_UPPER_LIMIT, PRICE_LOWER_LIMIT, TIME_SLEEP, OVERLAP_LIMIT)
