import main as logic

LINE_NOTIFY_TOKEN = "PMGSX5jGBYhpqIfQI3GwcGoLuxo4xxWQLx8Wf6y5Y2C"
SEARCH_URL = "https://jp.mercari.com/search?category_id=704&keyword=ds%E3%82%BD%E3%83%95%E3%83%88&status=on_sale"
LOOP_LIMIT = 10
PRICE_UPPER_LIMIT = 3001
PRICE_LOWER_LIMIT = 299
# 5minutes
TIME_SLEEP = 180

OVERLAP_LIMIT = 100

logic.main(LINE_NOTIFY_TOKEN, SEARCH_URL, LOOP_LIMIT, PRICE_UPPER_LIMIT, PRICE_LOWER_LIMIT, TIME_SLEEP, OVERLAP_LIMIT)

